version: '3.8'

services:
  db:
    container_name: db
    image: postgres:17

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lazerdigital
    ports:
      - 5433:5432
    volumes:
      - postgres_data_db:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
  redis:
    container_name: redis
    image: redis:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "6379:6379"
    restart: unless-stopped
    depends_on:
      - db

volumes:
  postgres_data_db: {}
  pgadmin_data: {}